/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios.Vuelo;

import Entidades.Aeropuerto;
import LogicaNegocio.LogicaNegocio;
import TableModels.VueloTableModel;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class FrmTablaVuelo extends javax.swing.JFrame {

    private static final FrmTablaVuelo INSTANCE=new FrmTablaVuelo();
    
    public static FrmTablaVuelo getInstance()
    {
        return INSTANCE;
    }
    
    /**
     * Creates new form FrmTablaVuelo
     */
    public FrmTablaVuelo() {
        initComponents();
        cargarVuelos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVuelos = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnbuscarVueloCodigo = new javax.swing.JMenuItem();
        mnbuscarVueloDestino = new javax.swing.JMenuItem();
        mnbuscarVueloDia = new javax.swing.JMenuItem();
        mnbuscarVueloDiaOpera = new javax.swing.JMenuItem();
        mnbuscarVueloOrigen = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVuelos);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel1.setText("Parametro de busqueda");

        jMenu1.setText("Buscar");

        mnbuscarVueloCodigo.setText("Buscar por codigo");
        mnbuscarVueloCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbuscarVueloCodigoActionPerformed(evt);
            }
        });
        jMenu1.add(mnbuscarVueloCodigo);

        mnbuscarVueloDestino.setText("Buscar por Destino");
        mnbuscarVueloDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbuscarVueloDestinoActionPerformed(evt);
            }
        });
        jMenu1.add(mnbuscarVueloDestino);

        mnbuscarVueloDia.setText("Buscar por dia");
        mnbuscarVueloDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbuscarVueloDiaActionPerformed(evt);
            }
        });
        jMenu1.add(mnbuscarVueloDia);

        mnbuscarVueloDiaOpera.setText("Buscar por dias que opera");
        mnbuscarVueloDiaOpera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbuscarVueloDiaOperaActionPerformed(evt);
            }
        });
        jMenu1.add(mnbuscarVueloDiaOpera);

        mnbuscarVueloOrigen.setText("Buscar por origen");
        mnbuscarVueloOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbuscarVueloOrigenActionPerformed(evt);
            }
        });
        jMenu1.add(mnbuscarVueloOrigen);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        tblVuelos.setModel(new VueloTableModel(LogicaNegocio.todosLosVuelos()));
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void mnbuscarVueloCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbuscarVueloCodigoActionPerformed
        LogicaNegocio.getVueloByCodigo(txtBusqueda.getText());
    }//GEN-LAST:event_mnbuscarVueloCodigoActionPerformed

    private void mnbuscarVueloDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbuscarVueloDestinoActionPerformed
      tblVuelos.setModel(new VueloTableModel(LogicaNegocio.getVueloByDestino(txtBusqueda.getText())));
      
    }//GEN-LAST:event_mnbuscarVueloDestinoActionPerformed

    private void mnbuscarVueloDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbuscarVueloDiaActionPerformed
        try 
        {
            tblVuelos.setModel(new VueloTableModel(LogicaNegocio.getVueloByDia((txtBusqueda.getText()))));
        } 
        catch (ParseException ex) 
        {
            Logger.getLogger(FrmTablaVuelo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnbuscarVueloDiaActionPerformed

    private void mnbuscarVueloDiaOperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbuscarVueloDiaOperaActionPerformed
        tblVuelos.setModel(new VueloTableModel(LogicaNegocio.getVueloByDiaOpera(txtBusqueda.getText())));
    }//GEN-LAST:event_mnbuscarVueloDiaOperaActionPerformed

    private void mnbuscarVueloOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbuscarVueloOrigenActionPerformed
        tblVuelos.setModel(new VueloTableModel(LogicaNegocio.getVueloByOrigen(txtBusqueda.getText())));
    }//GEN-LAST:event_mnbuscarVueloOrigenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTablaVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTablaVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTablaVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTablaVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTablaVuelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnbuscarVueloCodigo;
    private javax.swing.JMenuItem mnbuscarVueloDestino;
    private javax.swing.JMenuItem mnbuscarVueloDia;
    private javax.swing.JMenuItem mnbuscarVueloDiaOpera;
    private javax.swing.JMenuItem mnbuscarVueloOrigen;
    private javax.swing.JTable tblVuelos;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables


    
    
    
private void cargarVuelos()
{
    tblVuelos.setModel(new VueloTableModel(LogicaNegocio.todosLosVuelos()));
} 



}
