/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios.Compania;

import LogicaNegocio.LogicaNegocio;
import TableModels.AeropuertoTableModel;
import TableModels.CompaniaTableModel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Usuario
 */
public class FrmTablaCompania extends javax.swing.JFrame {

    private static final FrmTablaCompania INSTANCE=new FrmTablaCompania();
    
    public static FrmTablaCompania getInstance()
    {
        return INSTANCE;
    }
    
    /**
     * Creates new form FrmCompania
     */
    public FrmTablaCompania() {
        initComponents();
        cargarCompanias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompanias = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnbuscarCompaniaCodigo = new javax.swing.JMenuItem();
        mnbuscarCompaniaMunicipio = new javax.swing.JMenuItem();
        mnbuscarCompaniaNombre = new javax.swing.JMenuItem();
        mnbuscarCompaniaPrefijo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCompanias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCompanias);

        jLabel1.setText("Parametro de busqueda");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jMenu1.setText("Buscar");

        mnbuscarCompaniaCodigo.setText("Buscar por codigo");
        mnbuscarCompaniaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbuscarCompaniaCodigoActionPerformed(evt);
            }
        });
        jMenu1.add(mnbuscarCompaniaCodigo);

        mnbuscarCompaniaMunicipio.setText("Buscar por municipio");
        mnbuscarCompaniaMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbuscarCompaniaMunicipioActionPerformed(evt);
            }
        });
        jMenu1.add(mnbuscarCompaniaMunicipio);

        mnbuscarCompaniaNombre.setText("Buscar por nombre");
        mnbuscarCompaniaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbuscarCompaniaNombreActionPerformed(evt);
            }
        });
        jMenu1.add(mnbuscarCompaniaNombre);

        mnbuscarCompaniaPrefijo.setText("Buscar por prefijo");
        mnbuscarCompaniaPrefijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbuscarCompaniaPrefijoActionPerformed(evt);
            }
        });
        jMenu1.add(mnbuscarCompaniaPrefijo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusqueda)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        tblCompanias.setModel(new CompaniaTableModel(LogicaNegocio.todasLasCompanias()));
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void mnbuscarCompaniaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbuscarCompaniaCodigoActionPerformed
     List valores = new ArrayList();
       valores.add (LogicaNegocio.getCompaniaByCodigo(txtBusqueda.getText()));
       
       tblCompanias.setModel(new CompaniaTableModel(valores));
    }//GEN-LAST:event_mnbuscarCompaniaCodigoActionPerformed

    private void mnbuscarCompaniaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbuscarCompaniaNombreActionPerformed
       List valores = new ArrayList();
       valores.add (LogicaNegocio.getCompaniaByNombre(txtBusqueda.getText()));
       
       tblCompanias.setModel(new CompaniaTableModel(valores));
    }//GEN-LAST:event_mnbuscarCompaniaNombreActionPerformed

    private void mnbuscarCompaniaPrefijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbuscarCompaniaPrefijoActionPerformed
       List valores = new ArrayList();
       valores.add (LogicaNegocio.getCompaniaByPrefijo(txtBusqueda.getText()));
       
       tblCompanias.setModel(new CompaniaTableModel(valores));
    }//GEN-LAST:event_mnbuscarCompaniaPrefijoActionPerformed

    private void mnbuscarCompaniaMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbuscarCompaniaMunicipioActionPerformed
        tblCompanias.setModel(new CompaniaTableModel(LogicaNegocio.getCompaniaByMunicipio(txtBusqueda.getText())));
    }//GEN-LAST:event_mnbuscarCompaniaMunicipioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTablaCompania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTablaCompania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTablaCompania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTablaCompania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTablaCompania().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnbuscarCompaniaCodigo;
    private javax.swing.JMenuItem mnbuscarCompaniaMunicipio;
    private javax.swing.JMenuItem mnbuscarCompaniaNombre;
    private javax.swing.JMenuItem mnbuscarCompaniaPrefijo;
    private javax.swing.JTable tblCompanias;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables


private void cargarCompanias()
{
    tblCompanias.setModel(new CompaniaTableModel(LogicaNegocio.todasLasCompanias()));
}


}
