/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios.Aeropuerto;

import LogicaNegocio.LogicaNegocio;
import TableModels.AeropuertoTableModel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Usuario
 */
public class FrmTablaAeropuerto extends javax.swing.JFrame {

    private static final FrmTablaAeropuerto INSTANCE=new FrmTablaAeropuerto();
    
    public static FrmTablaAeropuerto getInstance()
    {
        return INSTANCE;
    }
    
    /**
     * Creates new form FrmTablaAeropuerto
     */
    public FrmTablaAeropuerto() {
        initComponents();
        cargarAeropuertos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAeropuertos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnbuscarAeroIATA = new javax.swing.JMenuItem();
        mnbuscarAeroMunicipio = new javax.swing.JMenuItem();
        mnbuscarAeroNombre = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblAeropuertos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAeropuertos);

        jLabel1.setText("Parametro de busqueda");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jMenu1.setText("Buscar");

        mnbuscarAeroIATA.setText("Buscar por codigo IATA");
        mnbuscarAeroIATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbuscarAeroIATAActionPerformed(evt);
            }
        });
        jMenu1.add(mnbuscarAeroIATA);

        mnbuscarAeroMunicipio.setText("Buscar por municipio");
        mnbuscarAeroMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbuscarAeroMunicipioActionPerformed(evt);
            }
        });
        jMenu1.add(mnbuscarAeroMunicipio);

        mnbuscarAeroNombre.setText("Buscar por nombre");
        mnbuscarAeroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbuscarAeroNombreActionPerformed(evt);
            }
        });
        jMenu1.add(mnbuscarAeroNombre);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        tblAeropuertos.setModel(new AeropuertoTableModel(LogicaNegocio.todosLosAeropuertos()));
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void mnbuscarAeroIATAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbuscarAeroIATAActionPerformed
        List valores = new ArrayList();
        valores.add (LogicaNegocio.getAeropuertoByIata(txtBusqueda.getText()));

        tblAeropuertos.setModel(new AeropuertoTableModel(valores));
    }//GEN-LAST:event_mnbuscarAeroIATAActionPerformed

    private void mnbuscarAeroMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbuscarAeroMunicipioActionPerformed
        tblAeropuertos.setModel(new AeropuertoTableModel(LogicaNegocio.getAeropuertoByMunicipio(txtBusqueda.getText())));
    }//GEN-LAST:event_mnbuscarAeroMunicipioActionPerformed

    private void mnbuscarAeroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbuscarAeroNombreActionPerformed
        List valores = new ArrayList();
        valores.add (LogicaNegocio.getAeropuertoByNombre(txtBusqueda.getText()));

        tblAeropuertos.setModel(new AeropuertoTableModel(valores));
    }//GEN-LAST:event_mnbuscarAeroNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTablaAeropuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTablaAeropuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTablaAeropuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTablaAeropuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTablaAeropuerto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnbuscarAeroIATA;
    private javax.swing.JMenuItem mnbuscarAeroMunicipio;
    private javax.swing.JMenuItem mnbuscarAeroNombre;
    private javax.swing.JTable tblAeropuertos;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

private void cargarAeropuertos()
{
    tblAeropuertos.setModel(new AeropuertoTableModel(LogicaNegocio.todosLosAeropuertos()));
}



}
