/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios.Aeropuerto;

import LogicaNegocio.LogicaNegocio;
import TableModels.AeropuertoTableModel;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.KeyStroke;

/**
 *
 * @author Usuario
 */
public class FrmTablaAeropuerto extends javax.swing.JFrame {
    
    JFXPanel jfxPanel;
    JFrame frame;
    

    private static final FrmTablaAeropuerto INSTANCE=new FrmTablaAeropuerto();
    
    public static FrmTablaAeropuerto getInstance()
    {
        return INSTANCE;
    }
    
    /**
     * Creates new form FrmTablaAeropuerto
     */
    public FrmTablaAeropuerto() {
        initComponents();
        cargarAeropuertos();
        setHelp();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAeropuertos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnbuscarAeroIATA = new javax.swing.JMenuItem();
        mnbuscarAeroMunicipio = new javax.swing.JMenuItem();
        mnbuscarAeroNombre = new javax.swing.JMenuItem();
        Jmenu2 = new javax.swing.JMenu();
        mnAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblAeropuertos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAeropuertos);

        jLabel1.setText("Parametro de busqueda");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jMenu1.setText("Buscar");

        mnbuscarAeroIATA.setText("Buscar por codigo IATA");
        mnbuscarAeroIATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbuscarAeroIATAActionPerformed(evt);
            }
        });
        jMenu1.add(mnbuscarAeroIATA);

        mnbuscarAeroMunicipio.setText("Buscar por municipio");
        mnbuscarAeroMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbuscarAeroMunicipioActionPerformed(evt);
            }
        });
        jMenu1.add(mnbuscarAeroMunicipio);

        mnbuscarAeroNombre.setText("Buscar por nombre");
        mnbuscarAeroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbuscarAeroNombreActionPerformed(evt);
            }
        });
        jMenu1.add(mnbuscarAeroNombre);

        jMenuBar1.add(jMenu1);

        Jmenu2.setText("Ayuda");

        mnAyuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnAyuda.setText("Ayuda general");
        mnAyuda.setActionCommand("");
        mnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAyudaActionPerformed(evt);
            }
        });
        Jmenu2.add(mnAyuda);

        jMenuBar1.add(Jmenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        tblAeropuertos.setModel(new AeropuertoTableModel(LogicaNegocio.todosLosAeropuertos()));
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void mnbuscarAeroIATAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbuscarAeroIATAActionPerformed
        List valores = new ArrayList();
        valores.add (LogicaNegocio.getAeropuertoByIata(txtBusqueda.getText()));

        tblAeropuertos.setModel(new AeropuertoTableModel(valores));
    }//GEN-LAST:event_mnbuscarAeroIATAActionPerformed

    private void mnbuscarAeroMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbuscarAeroMunicipioActionPerformed
        tblAeropuertos.setModel(new AeropuertoTableModel(LogicaNegocio.getAeropuertoByMunicipio(txtBusqueda.getText())));
    }//GEN-LAST:event_mnbuscarAeroMunicipioActionPerformed

    private void mnbuscarAeroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbuscarAeroNombreActionPerformed
        List valores = new ArrayList();
        valores.add (LogicaNegocio.getAeropuertoByNombre(txtBusqueda.getText()));

        tblAeropuertos.setModel(new AeropuertoTableModel(valores));
    }//GEN-LAST:event_mnbuscarAeroNombreActionPerformed

    private void mnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAyudaActionPerformed
        String url="https://daniel-garcia.gitbook.io/ayuda-tabla-aeropuertos/";
        openWebView(url);
    }//GEN-LAST:event_mnAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTablaAeropuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTablaAeropuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTablaAeropuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTablaAeropuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTablaAeropuerto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Jmenu2;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnAyuda;
    private javax.swing.JMenuItem mnbuscarAeroIATA;
    private javax.swing.JMenuItem mnbuscarAeroMunicipio;
    private javax.swing.JMenuItem mnbuscarAeroNombre;
    private javax.swing.JTable tblAeropuertos;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

private void cargarAeropuertos()
{
    tblAeropuertos.setModel(new AeropuertoTableModel(LogicaNegocio.todosLosAeropuertos()));
}



/*Metod para la implementacion de ayuda*/
private void setHelp() 
{
    /*Implementa la ayuda principal */
    jfxPanel = new JFXPanel();
    frame = new JFrame("Ayuda");
    frame.setSize(new Dimension(500, 500));
    frame.add(jfxPanel);
    
    Map<JComponent, String> contextualHelpMap = new HashMap<>();
    contextualHelpMap.put(mnbuscarAeroIATA, "https://app.gitbook.com/o/RhD4zGK8jzlmMlZ3zUII/s/hu6mwtmJCk7DPrhoOT4Q/ayuda-de-busqueda-de-aeropuerto-por-codigo-iata");
    contextualHelpMap.put(mnbuscarAeroMunicipio, "https://app.gitbook.com/o/RhD4zGK8jzlmMlZ3zUII/s/hu6mwtmJCk7DPrhoOT4Q/ayuda-de-busqueda-de-aeropuerto-por-municipio");
    contextualHelpMap.put(mnbuscarAeroNombre, "https://app.gitbook.com/o/RhD4zGK8jzlmMlZ3zUII/s/hu6mwtmJCk7DPrhoOT4Q/ayuda-de-busqueda-de-aeropuerto-por-nombre");
    // Se pueden agregar más elementos del mismo modo
    setContextualHelp(contextualHelpMap);

}


private void openWebView(String url) 
{
    Platform.runLater(() -> 
    {
        WebView webView = new WebView();
        WebEngine webEngine = webView.getEngine();
        webEngine.load(url);
        jfxPanel.setScene(new Scene(webView));
        frame.setVisible(true);
    });
}

private void setContextualHelp(Map<JComponent, String> map) 
{
    for (JComponent comp : map.keySet()) 
    {
        KeyStroke f1KeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0);
        InputMap inputMap = comp.getInputMap(JComponent.WHEN_FOCUSED);
        ActionMap actionMap = comp.getActionMap();
        inputMap.put(f1KeyStroke, "showContextualHelp");
        actionMap.put("showContextualHelp", new AbstractAction() 
        {
            @Override
            public void actionPerformed(ActionEvent e) 
            {
                String helpURL;
                helpURL = map.get(comp);
                openWebView(helpURL);
            }
        }
        );
    }
}



}
